-- 003: Seed HSK 2 Vocabulary — 150 words

DELETE FROM public.vocabulary WHERE hsk_level = 2;

INSERT INTO public.vocabulary (hanzi, pinyin, meaning_uz, meaning_en, hsk_level, example_sentence_zh, example_sentence_uz) VALUES
-- 1.1 Fe''llar (Verbs) — 50
('帮助', 'bāng zhù', 'Yordam bermoq', 'To help', 2, '我帮助妈妈做饭。', 'Men oyimga ovqat pishirishda yordam beraman.'),
('比较', 'bǐ jiào', 'Taqqoslamoq / Nisbatan', 'To compare', 2, '今天比较冷。', 'Bugun nisbatan sovuq.'),
('变', 'biàn', 'O''zgarmoq', 'To change', 2, '天气变了。', 'Ob-havo o''zgardi.'),
('出', 'chū', 'Chiqmoq', 'To exit', 2, '他出去了。', 'U chiqib ketdi.'),
('穿', 'chuān', 'Kiymoq', 'To wear', 2, '她穿红色衣服。', 'U qizil kiyim kiydi.'),
('带', 'dài', 'Olib kelmoq', 'To bring/take', 2, '请带护照。', 'Pasportingizni olib keling.'),
('到', 'dào', 'Yetib kelmoq', 'To arrive', 2, '我到家了。', 'Men uyga yetib keldim.'),
('等', 'děng', 'Kutmoq', 'To wait', 2, '等一下。', 'Bir oz kuting.'),
('懂', 'dǒng', 'Tushunmoq', 'To understand', 2, '我不懂。', 'Men tushunmayman.'),
('发', 'fā', 'Yubormoq', 'To send', 2, '我给你发了邮件。', 'Sizga email yubordim.'),
('告诉', 'gào su', 'Aytmoq', 'To tell', 2, '请告诉我你的名字。', 'Menga ismingizni ayting.'),
('跟', 'gēn', 'Ergashmoq / Bilan', 'To follow / With', 2, '我跟他一起去。', 'Men u bilan birga boraman.'),
('过', 'guò', 'O''tmoq', 'To pass', 2, '我在这里过了两年。', 'Men bu yerda ikki yil o''tkazdim.'),
('换', 'huàn', 'Almashtirmoq', 'To exchange', 2, '我想换钱。', 'Yuan alishtirishni xohlayman.'),
('介绍', 'jiè shào', 'Tanishtirmoq', 'To introduce', 2, '我来介绍一下。', 'Ijozat bering, tanishtirayin.'),
('进', 'jìn', 'Kirmoq', 'To enter', 2, '请进！', 'Marhamat, kiring!'),
('觉得', 'jué de', 'His qilmoq', 'To feel/think', 2, '我觉得很好。', 'Menga juda yaxshi his qilinadi.'),
('开始', 'kāi shǐ', 'Boshlamoq', 'To begin', 2, '上课开始了。', 'Dars boshlandi.'),
('考试', 'kǎo shì', 'Imtihon bermoq', 'To take exam', 2, '明天有考试。', 'Ertaga imtihonim bor.'),
('离开', 'lí kāi', 'Ketmoq', 'To leave', 2, '他离开了北京。', 'U Pekinni tark etdi.'),
('了解', 'liǎo jiě', 'Tushunmoq / Bilmoq', 'To understand/know', 2, '我了解他。', 'Men uni bilaman.'),
('练习', 'liàn xí', 'Mashq qilmoq', 'To practice', 2, '我练习说中文。', 'Men xitoycha gapirish mashq qilaman.'),
('旅游', 'lǚ yóu', 'Sayohat qilmoq', 'To travel', 2, '我喜欢旅游。', 'Men sayohat qilishni yaxshi ko''raman.'),
('拿', 'ná', 'Olmoq / Tutmoq', 'To take/hold', 2, '他拿着书。', 'U kitob ushlab turibdi.'),
('能', 'néng', 'Qila olmoq', 'Can / Be able to', 2, '我能帮你。', 'Men sizga yordam bera olaman.'),
('跑', 'pǎo', 'Yugurmoq', 'To run', 2, '我每天跑步。', 'Men har kuni yuguraman.'),
('骑', 'qí', 'Minmoq (velosiped)', 'To ride', 2, '我骑自行车去学校。', 'Men velosipedda maktabga boraman.'),
('让', 'ràng', 'Ruxsat bermoq', 'To let/allow', 2, '请让我帮你。', 'Menga yordam berishga ruxsat bering.'),
('认识', 'rèn shi', 'Tanish bo''lmoq', 'To know (person)', 2, '我认识他。', 'Men uni taniman.'),
('上', 'shàng', 'Chiqmoq / Bormoq', 'To go up/attend', 2, '我上班了。', 'Ishga bordim.'),
('生病', 'shēng bìng', 'Kasal bo''lmoq', 'To get sick', 2, '我生病了。', 'Men kasal bo''ldim.'),
('试', 'shì', 'Sinab ko''rmoq', 'To try', 2, '请试试。', 'Buni sinab ko''ring.'),
('送', 'sòng', 'Kuzatmoq', 'To send/give', 2, '我送你回家。', 'Seni uyga kuzataman.'),
('踢', 'tī', 'Tepmoq (futbol)', 'To kick', 2, '他们踢足球。', 'Ular futbol o''ynaydi.'),
('跳舞', 'tiào wǔ', 'Raqs tushmoq', 'To dance', 2, '她会跳舞。', 'U raqs tusha oladi.'),
('听说', 'tīng shuō', 'Eshitmoq (gapirishicha)', 'Heard that', 2, '听说他来了。', 'U keladi deb eshitdim.'),
('玩', 'wán', 'O''ynamoq', 'To play', 2, '孩子们在玩。', 'Bolalar o''ynayapti.'),
('问', 'wèn', 'So''ramoq', 'To ask', 2, '我想问你一个问题。', 'Sizdan bir savol so''ramoqchiman.'),
('希望', 'xī wàng', 'Umid qilmoq', 'To hope/wish', 2, '祝你成功。', 'Sizga muvaffaqiyat tilayman.'),
('需要', 'xū yào', 'Kerak bo''lmoq', 'To need', 2, '我需要帮助。', 'Mening yordamga ehtiyojim bor.'),
('游泳', 'yóu yǒng', 'Suzmoq', 'To swim', 2, '我喜欢游泳。', 'Men suzishni yaxshi ko''raman.'),
('遇到', 'yù dào', 'Uchrashmoq', 'To run into', 2, '我遇到了老朋友。', 'Eski do''stimni uchratib qoldim.'),
('走', 'zǒu', 'Yurmoq / Ketmoq', 'To walk', 2, '我们走吧！', 'Keling, ketamiz!'),
('打', 'dǎ', 'Urmoq / O''ynamoq', 'To hit/play', 2, '我打篮球。', 'Men basketbol o''ynayman.'),
('唱', 'chàng', 'Qo''shiq aytmoq', 'To sing', 2, '她喜欢唱歌。', 'U qo''shiq aytishni yaxshi ko''radi.'),
('搬', 'bān', 'Ko''chirmoq', 'To move', 2, '我们搬家了。', 'Biz ko''chib ketamiz.'),
('迟到', 'chí dào', 'Kechikmoq', 'To be late', 2, '对不起，我迟到了。', 'Kechirasiz, kechikdim.'),
('回答', 'huí dá', 'Javob bermoq', 'To answer', 2, '请回答我的问题。', 'Iltimos, savolimga javob bering.'),
('发现', 'fā xiàn', 'Topmoq', 'To discover', 2, '我发现了一个新咖啡馆。', 'Yangi qahvaxona topdim.'),
('刷牙', 'shuā yá', 'Tish tozalamoq', 'Brush teeth', 2, '早上刷牙。', 'Ertalab tish tozalayman.'),
('洗澡', 'xǐ zǎo', 'Cho''milmoq', 'Take a shower', 2, '晚上洗澡。', 'Kechqurun dush qabul qilaman.'),

-- 1.2 Otlar (Nouns) — 65
('班', 'bān', 'Sinf / Guruh', 'Class / Group', 2, '我们班有三十个学生。', 'Mening sinfimda o''ttiz o''quvchi bor.'),
('报纸', 'bào zhǐ', 'Gazeta', 'Newspaper', 2, '爸爸看报纸。', 'Dadam gazeta o''qiydi.'),
('宾馆', 'bīn guǎn', 'Mehmonxona', 'Hotel', 2, '我住在宾馆。', 'Men mehmonxonada turaman.'),
('超市', 'chāo shì', 'Supermarket', 'Supermarket', 2, '我去超市买东西。', 'Supermarketga narsa sotib olishga boraman.'),
('成绩', 'chéng jì', 'Natija / Baho', 'Grade / Result', 2, '我的成绩很好。', 'Mening baholarim yaxshi.'),
('城市', 'chéng shì', 'Shahar', 'City', 2, '北京是大城市。', 'Pekin katta shahar.'),
('地方', 'dì fang', 'Joy / Manzil', 'Place', 2, '这个地方很美。', 'Bu joy juda chiroyli.'),
('地铁', 'dì tiě', 'Metro', 'Subway', 2, '我坐地铁上班。', 'Metro bilan ishga boraman.'),
('东西', 'dōng xi', 'Narsa / Buyum', 'Thing', 2, '这是什么东西？', 'Bu narsa nima?'),
('房间', 'fáng jiān', 'Xona', 'Room', 2, '我的房间很干净。', 'Mening xonam juda toza.'),
('附近', 'fù jìn', 'Yaqin atrofida', 'Nearby', 2, '附近有超市。', 'Yaqin atrofda supermarket bor.'),
('公共汽车', 'gōng gòng qì chē', 'Avtobus', 'Bus', 2, '我坐公共汽车。', 'Men avtobusda boraman.'),
('公司', 'gōng sī', 'Kompaniya', 'Company', 2, '我在公司工作。', 'Men kompaniyada ishlayman.'),
('护照', 'hù zhào', 'Pasport', 'Passport', 2, '我的护照在哪里？', 'Mening pasportim qayerda?'),
('机场', 'jī chǎng', 'Aeroport', 'Airport', 2, '我去机场。', 'Men aeroportga boraman.'),
('价格', 'jià gé', 'Narx', 'Price', 2, '这个价格怎么样？', 'Bu narx qanday?'),
('假期', 'jiǎ qī', 'Ta''til', 'Holiday', 2, '假期你去哪里？', 'Ta''tilda qayerga borasiz?'),
('节日', 'jié rì', 'Bayram', 'Holiday / Festival', 2, '春节是中国最大的节日。', 'Bahor bayrami Xitoyning katta bayrami.'),
('经理', 'jīng lǐ', 'Menejer / Rahbar', 'Manager', 2, '他是我们的经理。', 'U bizning menejerimiz.'),
('镜子', 'jìng zi', 'Ko''zgu', 'Mirror', 2, '我照镜子。', 'Ko''zguga qarayman.'),
('空调', 'kōng tiáo', 'Konditsioner', 'Air conditioner', 2, '请打开空调。', 'Konditsionerni yoqing.'),
('路', 'lù', 'Yo''l / Ko''cha', 'Road / Way', 2, '这条路很长。', 'Bu yo''l juda uzun.'),
('旅行', 'lǚ xíng', 'Sayohat', 'Trip / Travel', 2, '我计划旅行。', 'Men sayohat rejalashtiraman.'),
('猫', 'māo', 'Mushuk', 'Cat', 2, '我有一只猫。', 'Mening bitta mushugim bor.'),
('面包', 'miàn bāo', 'Non', 'Bread', 2, '早饭吃面包。', 'Ertalabki ovqatda non yeyman.'),
('鸟', 'niǎo', 'Qush', 'Bird', 2, '窗外有一只小鸟。', 'Derazadan tashqarida kichik qush bor.'),
('牛奶', 'niú nǎi', 'Sut', 'Milk', 2, '我每天喝牛奶。', 'Men har kuni sut ichaman.'),
('旁边', 'páng biān', 'Yon tarafda', 'Next to / Beside', 2, '学校旁边有超市。', 'Maktab yonida supermarket bor.'),
('票', 'piào', 'Bilet / Chipta', 'Ticket', 2, '我买了两张票。', 'Ikkita chipta sotib oldim.'),
('问题', 'wèn tí', 'Savol / Muammo', 'Question / Problem', 2, '我有一个问题。', 'Menda bitta savol bor.'),
('西瓜', 'xī guā', 'Tarvuz', 'Watermelon', 2, '西瓜很甜。', 'Tarvuz juda shirin.'),
('新闻', 'xīn wén', 'Yangiliklar', 'News', 2, '我看新闻。', 'Men yangiliklar ko''raman.'),
('行李', 'xíng li', 'Bagaj', 'Luggage', 2, '行李很重。', 'Bagajim juda og''ir.'),
('熊猫', 'xióng māo', 'Panda', 'Panda', 2, '我喜欢熊猫。', 'Men pandani yaxshi ko''raman.'),
('眼睛', 'yǎn jing', 'Ko''z', 'Eye', 2, '她的眼睛很大。', 'Uning katta ko''zlari bor.'),
('颜色', 'yán sè', 'Rang', 'Color', 2, '你喜欢什么颜色？', 'Qaysi rangni yaxshi ko''rasiz?'),
('药', 'yào', 'Dori', 'Medicine', 2, '我吃了药。', 'Dori ichdim.'),
('椅子', 'yǐ zi', 'Stul', 'Chair', 2, '请坐椅子。', 'Iltimos, stulga o''tiring.'),
('音乐', 'yīn yuè', 'Musiqa', 'Music', 2, '我喜欢听音乐。', 'Men musiqa tinglashni yaxshi ko''raman.'),
('鱼', 'yú', 'Baliq', 'Fish', 2, '我吃鱼。', 'Men baliq yeyman.'),
('运动', 'yùn dòng', 'Sport / Harakat', 'Sport / Exercise', 2, '我喜欢运动。', 'Men sport bilan shug''ullanishni yaxshi ko''raman.'),
('站', 'zhàn', 'Bekat', 'Station / Stop', 2, '下一站在哪里？', 'Keyingi bekat qayerda?'),
('照片', 'zhào piàn', 'Rasm / Fotosurat', 'Photo', 2, '这张照片很漂亮。', 'Bu fotosurat juda chiroyli.'),
('桌子', 'zhuō zi', 'Stol', 'Table', 2, '书在桌子上。', 'Kitob stolda.'),
('自行车', 'zì xíng chē', 'Velosiped', 'Bicycle', 2, '他骑自行车。', 'U velosiped minadi.'),
('足球', 'zú qiú', 'Futbol', 'Football', 2, '我喜欢踢足球。', 'Men futbol o''ynashni yaxshi ko''raman.'),
('作业', 'zuò yè', 'Uy vazifa', 'Homework', 2, '我做作业。', 'Men uy vazifasini qilaman.'),
('左边', 'zuǒ biān', 'Chap tomon', 'Left side', 2, '银行在左边。', 'Bank chap tomonda.'),
('右边', 'yòu biān', 'O''ng tomon', 'Right side', 2, '超市在右边。', 'Supermarket o''ng tomonda.'),
('前面', 'qián miàn', 'Oldinda', 'In front', 2, '学校在前面。', 'Maktab oldinda.'),
('后面', 'hòu miàn', 'Orqada', 'Behind', 2, '公园在后面。', 'Park orqada.'),
('中间', 'zhōng jiān', 'O''rtada', 'In the middle', 2, '他坐在中间。', 'U o''rtada o''tiradi.'),
('里面', 'lǐ miàn', 'Ichida', 'Inside', 2, '里面很暖和。', 'Ichida juda iliq.'),
('上面', 'shàng miàn', 'Ustida', 'Above / On top', 2, '书在上面。', 'Kitob ustida.'),
('下面', 'xià miàn', 'Ostida / Pastida', 'Below / Under', 2, '猫在桌子下面。', 'Mushuk stolning ostida.'),
('狗', 'gǒu', 'It / Kuchuk', 'Dog', 2, '他有一只狗。', 'Uning bitta iti bor.'),
('花', 'huā', 'Gul', 'Flower', 2, '这些花很漂亮。', 'Bu gullar juda chiroyli.'),
('季节', 'jì jié', 'Fasl', 'Season', 2, '你喜欢哪个季节？', 'Qaysi faslni ko''proq yaxshi ko''rasiz?'),
('春天', 'chūn tiān', 'Bahor', 'Spring', 2, '春天很美。', 'Bahor juda chiroyli.'),
('夏天', 'xià tiān', 'Yoz', 'Summer', 2, '夏天很热。', 'Yozda juda issiq bo''ladi.'),
('秋天', 'qiū tiān', 'Kuz', 'Autumn', 2, '秋天叶子变红了。', 'Kuzda barglar qizaradi.'),
('冬天', 'dōng tiān', 'Qish', 'Winter', 2, '冬天很冷。', 'Qishda juda sovuq bo''ladi.'),
('声音', 'shēng yīn', 'Ovoz / Tovush', 'Sound / Voice', 2, '这个声音很大。', 'Bu ovoz juda baland.'),
('洗手间', 'xǐ shǒu jiān', 'Hojatxona', 'Restroom', 2, '洗手间在哪里？', 'Hojatxona qayerda?'),
('水果', 'shuǐ guǒ', 'Meva', 'Fruit', 2, '我喜欢吃水果。', 'Men meva yeyishni yaxshi ko''raman.'),
('蔬菜', 'shū cài', 'Sabzavot', 'Vegetables', 2, '多吃蔬菜有益。', 'Ko''proq sabzavot yeyish foydali.'),
('信', 'xìn', 'Xat / Maktub', 'Letter', 2, '我收到一封信。', 'Bitta xat oldim.'),

-- 1.3 Sifatlar (Adjectives) — 25
('矮', 'ǎi', 'Past bo''yli', 'Short (height)', 2, '他很矮。', 'U juda past bo''yli.'),
('干净', 'gān jìng', 'Toza', 'Clean', 2, '房间很干净。', 'Xona juda toza.'),
('脏', 'zāng', 'Iflos', 'Dirty', 2, '衣服脏了。', 'Kiyim ifloslandi.'),
('胖', 'pàng', 'To''la / Semiz', 'Fat / Chubby', 2, '他有点胖。', 'U biroz to''la.'),
('瘦', 'shòu', 'Oriq', 'Thin / Slim', 2, '她很瘦。', 'U juda oriq.'),
('重', 'zhòng', 'Og''ir', 'Heavy', 2, '这个箱子很重。', 'Bu quti juda og''ir.'),
('轻', 'qīng', 'Yengil', 'Light', 2, '这个包很轻。', 'Bu sumka juda yengil.'),
('难', 'nán', 'Qiyin', 'Difficult', 2, '这个题很难。', 'Bu misol juda qiyin.'),
('容易', 'róng yì', 'Oson', 'Easy', 2, '这很容易。', 'Bu juda oson.'),
('快', 'kuài', 'Tez', 'Fast / Quick', 2, '他走得很快。', 'U juda tez yuradi.'),
('慢', 'màn', 'Sekin', 'Slow', 2, '火车很慢。', 'Poyezd juda sekin.'),
('新', 'xīn', 'Yangi', 'New', 2, '这是新书。', 'Bu yangi kitob.'),
('旧', 'jiù', 'Eski', 'Old (object)', 2, '这双鞋很旧了。', 'Bu poyabzal juda eski.'),
('早', 'zǎo', 'Erta', 'Early', 2, '你来得很早。', 'Siz juda erta keldingiz.'),
('晚', 'wǎn', 'Kech', 'Late', 2, '今天睡得很晚。', 'Bugun juda kech uxladim.'),
('正确', 'zhèng què', 'To''g''ri', 'Correct', 2, '你的答案正确。', 'Javobingiz to''g''ri.'),
('错', 'cuò', 'Noto''g''ri / Xato', 'Wrong / Mistaken', 2, '这个答案错了。', 'Bu javob noto''g''ri.'),
('近', 'jìn', 'Yaqin', 'Near / Close', 2, '学校离家很近。', 'Maktab uyimga juda yaqin.'),
('远', 'yuǎn', 'Uzoq', 'Far', 2, '北京很远。', 'Pekin bu yerdan juda uzoq.'),
('暖和', 'nuǎn huo', 'Iliq', 'Warm', 2, '春天很暖和。', 'Bahorda juda iliq bo''ladi.'),
('有名', 'yǒu míng', 'Mashhur / Taniqli', 'Famous', 2, '他是有名的歌手。', 'U mashhur qo''shiqchi.'),
('有趣', 'yǒu qù', 'Qiziqarli', 'Interesting', 2, '这本书很有趣。', 'Bu kitob juda qiziqarli.'),
('方便', 'fāng biàn', 'Qulay', 'Convenient', 2, '地铁很方便。', 'Metro juda qulay.'),
('一样', 'yī yàng', 'Xuddi shunday', 'The same / Alike', 2, '我们一样高。', 'Biz xuddi bir xil balandlikda.'),
('对', 'duì', 'To''g''ri / Ga qarab', 'Correct / Toward', 2, '你说得对。', 'Siz to''g''ri aytdingiz.'),

-- 1.4 Ravishlar (Adverbs) — 15
('一般', 'yī bān', 'Odatda / O''rtacha', 'Usually / Average', 2, '我一般七点起床。', 'Men odatda soat yettida uyg''onaman.'),
('常常', 'cháng cháng', 'Tez-tez / Ko''pincha', 'Often', 2, '他常常迟到。', 'U ko''pincha kechikadi.'),
('有时候', 'yǒu shí hou', 'Ba''zan', 'Sometimes', 2, '我有时候打篮球。', 'Men ba''zan basketbol o''ynayman.'),
('从来', 'cóng lái', 'Hech qachon (inkor)', 'Never (with neg)', 2, '我从来不吸烟。', 'Men hech qachon chekmaganman.'),
('已经', 'yǐ jīng', 'Allaqachon', 'Already', 2, '我已经吃了。', 'Men allaqachon yedim.'),
('还', 'hái', 'Hali ham / Yana', 'Still / Also', 2, '他还没来。', 'U hali ham kelmadi.'),
('再', 'zài', 'Yana / Qayta', 'Again / One more', 2, '请再说一遍。', 'Yana bir marta ayting.'),
('刚才', 'gāng cái', 'Hozirgina', 'Just now', 2, '他刚才打电话了。', 'U hozirgina telefon qildi.'),
('马上', 'mǎ shàng', 'Darhol', 'Right away', 2, '我马上来。', 'Men darhol kelaman.'),
('其实', 'qí shí', 'Aslida / Haqiqatda', 'Actually', 2, '其实我知道。', 'Aslida men bilaman.'),
('当然', 'dāng rán', 'Albatta', 'Of course', 2, '当然可以！', 'Albatta mumkin!'),
('一直', 'yī zhí', 'To''xtovsiz / Doimo', 'Continuously', 2, '他一直在学习。', 'U doimo o''qib yuribdi.'),
('一下', 'yī xià', 'Bir oz / Biroz', 'A little / Once', 2, '等一下！', 'Bir oz kuting!'),
('先', 'xiān', 'Avval / Birinchi', 'First', 2, '我先去。', 'Men avval boraman, sen keyin.'),
('别', 'bié', 'Qilma / Yurma', 'Don''t', 2, '别担心！', 'Tashvishlanma!'),

-- 1.5 Bog''lovchilar (Conjunctions) — 8
('所以', 'suǒ yǐ', 'Shuning uchun', 'Therefore / So', 2, '他生病了，所以没来。', 'U kasal bo''lgani uchun kelmadi.'),
('因为', 'yīn wèi', 'Chunki / Sababi', 'Because', 2, '因为下雨，我没去。', 'Yomg''ir yoqqani uchun bormadam.'),
('但是', 'dàn shì', 'Lekin / Ammo', 'But / However', 2, '很累，但是我去了。', 'Charchadim, lekin bordim.'),
('如果', 'rú guǒ', 'Agar', 'If', 2, '如果你来，我很高兴。', 'Agar kelsangiz, juda xursand bo''laman.'),
('虽然', 'suī rán', 'Garchi... bo''lsa ham', 'Although', 2, '虽然难，但是我想学。', 'Qiyin bo''lsa ham, o''rganmoqchiman.'),
('或者', 'huò zhě', 'Yoki', 'Or', 2, '我喝茶或者咖啡。', 'Men choy yoki qahva ichaman.'),
('而且', 'ér qiě', 'Bundan tashqari / Ham', 'Moreover / And', 2, '他聪明，而且勤快。', 'U aqlli, bundan tashqari mehnatsevar.'),
('然后', 'rán hòu', 'Keyin / Undan so''ng', 'Then / After that', 2, '先吃饭，然后休息。', 'Avval ovqat ye, keyin dam ol.'),

-- 1.6 Maxsus so''zlar (Modal verbs & Prepositions) — 6
('可以', 'kě yǐ', 'Mumkin / Bo''ladi', 'Can / May', 2, '可以进吗？', 'Kirish mumkinmi?'),
('会', 'huì', 'Bilmoq / Qila olmoq', 'Can / Know how to', 2, '你会开车吗？', 'Mashina haydashni bilasizmi?'),
('应该', 'yīng gāi', 'Kerak / Lozim', 'Should / Ought to', 2, '你应该多喝水。', 'Ko''proq suv ichishingiz kerak.'),
('向', 'xiàng', 'Tomon / Qarab', 'Toward / Direction', 2, '向左走。', 'Chapga yuring.'),
('从', 'cóng', 'Dan (boshlab)', 'From', 2, '我从学校来。', 'Men maktabdan kelaman.'),
('离', 'lí', 'Dan (masofa)', 'From (distance)', 2, '这里离机场很远。', 'Bu yerdan aeroport juda uzoq.');
